### ISSUE TITLE
Formio error during local deployment (Ansible)

### ISSUE THREAD

**Issue by baddlan** [DigitalState/Platform#8]
I am just adding this here for reference.
```
fatal: [server]: FAILED! => 
{
  "changed": true,
  "cmd": "docker-compose -f /srv/service/formio/docker-compose.yml up -d",
  "delta": "0:01:28.197018",
  "end": "2017-11-02 19:08:12.561754",
  "failed": true,
  "msg": "non-zero return code",
  "rc": 1,
  "start": "2017-11-02 19:06:44.364736",
  "stderr": "Building formio_formio\nService 'formio_formio' failed to build: The command '/bin/sh -c cd /opt/formio && npm rebuild' returned a non-zero code: 1",
  "stderr_lines": [
    "Building formio_formio",
    "Service 'formio_formio' failed to build: The command '/bin/sh -c cd /opt/formio && npm rebuild' returned a non-zero code: 1"
  ],
  "stdout": "Step 1/9 : FROM mhart/alpine-node:6.10.3\n ---> 20befb1f69f5\nStep 2/9 : RUN apk add --no-cache make gcc g++ python\n ---> Using cache\n ---> 62904d219526\nStep 3/9 : RUN mkdir -p /opt\n ---> Using cache\n ---> 73c423e6b138\nStep 4/9 : ADD formio /opt/formio\n ---> e32ae2809932\nStep 5/9 : RUN cd /opt/formio && npm rebuild\n ---> Running in f1c5ff4110b7\n\n> bcrypt@0.8.7 install /opt/formio/node_modules/bcrypt\n> node-gyp rebuild\n\n\u001b[91mgyp\u001b[0m\u001b[91m WARN\u001b[0m\u001b[91m install got an error, rolling back install\n\u001b[0m\u001b[91mgyp ERR! configure error \ngyp ERR! stack\u001b[0m\u001b[91m Error: getaddrinfo EAI_AGAIN nodejs.org:443\ngyp ERR! stack     at Object.exports._errnoException (util.js:1018:11)\ngyp ERR! stack     at errnoException (dns.js:33:15)\ngyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)\n\u001b[0m\u001b[91mgyp ERR! System Linux 4.9.49-moby\ngyp ERR! command \"/usr/bin/node\" \"/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"\ngyp \u001b[0m\u001b[91mERR! cwd /opt/formio/node_modules/bcrypt\ngyp ERR! node -v v6.10.3\n\u001b[0m\u001b[91mgyp ERR! node-gyp -v v3.4.0\n\u001b[0m\u001b[91mgyp ERR! not ok \n\u001b[0m\u001b[91m\n\u001b[0m\u001b[91mnpm ERR! Linux 4.9.49-moby\n\u001b[0m\u001b[91mnpm ERR! argv \"/usr/bin/node\" \"/usr/bin/npm\" \"rebuild\"\nnpm ERR! node v6.10.3\nnpm ERR!\u001b[0m\u001b[91m npm  v3.10.10\n\u001b[0m\u001b[91mnpm ERR! code ELIFECYCLE\nnpm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR!\u001b[0m\u001b[91m Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.\nnpm ERR! Make sure you have the latest version of node.js and npm installed.\nnpm ERR! If you do, this is most likely a problem with the bcrypt package,\nnpm ERR! not with npm itself.\nnpm ERR! Tell the author that this fails on your system:\nnpm ERR!\u001b[0m\u001b[91m     node-gyp rebuild\nnpm ERR! You can get information on how to open an issue for this project with:\nnpm ERR!     npm bugs bcrypt\nnpm ERR! Or if that isn't available, you can get their info via:\nnpm ERR!     npm owner ls bcrypt\nnpm ERR!\u001b[0m\u001b[91m There is likely additional logging output above.\n\u001b[0m\u001b[91m\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /opt/formio/npm-debug.log\n\u001b[0m",
  "stdout_lines": [
    "Step 1/9 : FROM mhart/alpine-node:6.10.3",
    " ---> 20befb1f69f5",
    "Step 2/9 : RUN apk add --no-cache make gcc g++ python",
    " ---> Using cache",
    " ---> 62904d219526",
    "Step 3/9 : RUN mkdir -p /opt",
    " ---> Using cache",
    " ---> 73c423e6b138",
    "Step 4/9 : ADD formio /opt/formio",
    " ---> e32ae2809932",
    "Step 5/9 : RUN cd /opt/formio && npm rebuild",
    " ---> Running in f1c5ff4110b7",
    "",
    "> bcrypt@0.8.7 install /opt/formio/node_modules/bcrypt",
    "> node-gyp rebuild",
    "",
    "\u001b[91mgyp\u001b[0m\u001b[91m WARN\u001b[0m\u001b[91m install got an error, rolling back install",
    "\u001b[0m\u001b[91mgyp ERR! configure error ",
    "gyp ERR! stack\u001b[0m\u001b[91m Error: getaddrinfo EAI_AGAIN nodejs.org:443",
    "gyp ERR! stack     at Object.exports._errnoException (util.js:1018:11)",
    "gyp ERR! stack     at errnoException (dns.js:33:15)",
    "gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)",
    "\u001b[0m\u001b[91mgyp ERR! System Linux 4.9.49-moby",
    "gyp ERR! command \"/usr/bin/node\" \"/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"",
    "gyp \u001b[0m\u001b[91mERR! cwd /opt/formio/node_modules/bcrypt",
    "gyp ERR! node -v v6.10.3",
    "\u001b[0m\u001b[91mgyp ERR! node-gyp -v v3.4.0",
    "\u001b[0m\u001b[91mgyp ERR! not ok ",
    "\u001b[0m\u001b[91m",
    "\u001b[0m\u001b[91mnpm ERR! Linux 4.9.49-moby",
    "\u001b[0m\u001b[91mnpm ERR! argv \"/usr/bin/node\" \"/usr/bin/npm\" \"rebuild\"",
    "npm ERR! node v6.10.3",
    "npm ERR!\u001b[0m\u001b[91m npm  v3.10.10",
    "\u001b[0m\u001b[91mnpm ERR! code ELIFECYCLE",
    "npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`",
    "npm ERR! Exit status 1",
    "npm ERR! ",
    "npm ERR!\u001b[0m\u001b[91m Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.",
    "npm ERR! Make sure you have the latest version of node.js and npm installed.",
    "npm ERR! If you do, this is most likely a problem with the bcrypt package,",
    "npm ERR! not with npm itself.",
    "npm ERR! Tell the author that this fails on your system:",
    "npm ERR!\u001b[0m\u001b[91m     node-gyp rebuild",
    "npm ERR! You can get information on how to open an issue for this project with:",
    "npm ERR!     npm bugs bcrypt",
    "npm ERR! Or if that isn't available, you can get their info via:",
    "npm ERR!     npm owner ls bcrypt",
    "npm ERR!\u001b[0m\u001b[91m There is likely additional logging output above.",
    "\u001b[0m\u001b[91m",
    "npm ERR! Please include the following file with any support request:",
    "npm ERR!     /opt/formio/npm-debug.log",
    "\u001b[0m"
  ]
}
```

**Comment by marioprudhomme** [comment]
Fixed.
